"""changed

Revision ID: 110394c58d78
Revises: 0a8e50b34f94
Create Date: 2024-05-24 16:07:36.072094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110394c58d78'
down_revision = '0a8e50b34f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_start')
        batch_op.create_index(batch_op.f('ix_events_start'), ['start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_start'))
        batch_op.create_index('ix_events_start', ['start'], unique=False)

    # ### end Alembic commands ###
