"""empty message

Revision ID: 11ed04c0fd2d
Revises: d8cf973ef621
Create Date: 2024-05-22 09:05:23.443060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ed04c0fd2d'
down_revision = 'd8cf973ef621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_date')
        batch_op.create_index(batch_op.f('ix_events_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_date'))
        batch_op.create_index('ix_events_date', ['date'], unique=False)

    # ### end Alembic commands ###
