"""changed

Revision ID: 3b5667f0d93f
Revises: 77fe0ddde9f8
Create Date: 2024-05-27 19:40:52.654173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5667f0d93f'
down_revision = '77fe0ddde9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_event_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_events_start')
        batch_op.create_index(batch_op.f('ix_events_start'), ['start'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_events_parent_event_id_events'), 'events', ['parent_event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_events_parent_event_id_events'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_events_start'))
        batch_op.create_index('ix_events_start', ['start'], unique=False)
        batch_op.drop_column('parent_event_id')

    # ### end Alembic commands ###
