"""updated models.py events, event_instances, event_exceptions, user_parameters and user_tem_params

Revision ID: 51100bcf3e5b
Revises: ce430b87d0d1
Create Date: 2024-05-17 08:28:21.147504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51100bcf3e5b'
down_revision = 'ce430b87d0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_parameters', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
