"""changed events.sql

Revision ID: 52574b2ac4ee
Revises: abee7aab885e
Create Date: 2024-05-22 20:23:44.140927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52574b2ac4ee'
down_revision = 'abee7aab885e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_start')
        batch_op.create_index(batch_op.f('ix_events_start'), ['start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_start'))
        batch_op.create_index('ix_events_start', ['start'], unique=False)

    # ### end Alembic commands ###
