"""empty message

Revision ID: 913e77f0dd49
Revises: baad669dd03c
Create Date: 2024-05-18 11:33:59.427523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913e77f0dd49'
down_revision = 'baad669dd03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_date')
        batch_op.create_index(batch_op.f('ix_events_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_date'))
        batch_op.create_index('ix_events_date', ['date'], unique=False)

    # ### end Alembic commands ###
