"""empty message

Revision ID: baad669dd03c
Revises: 469b4e9a2457
Create Date: 2024-05-18 08:08:46.876271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baad669dd03c'
down_revision = '469b4e9a2457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_date')
        batch_op.create_index(batch_op.f('ix_events_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_date'))
        batch_op.create_index('ix_events_date', ['date'], unique=False)

    # ### end Alembic commands ###
