"""changed events.sql

Revision ID: c17ca694f285
Revises: 52574b2ac4ee
Create Date: 2024-05-22 20:30:32.576163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17ca694f285'
down_revision = '52574b2ac4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_start')
        batch_op.create_index(batch_op.f('ix_events_start'), ['start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_start'))
        batch_op.create_index('ix_events_start', ['start'], unique=False)

    # ### end Alembic commands ###
