"""changed

Revision ID: e3a84b8e2d17
Revises: 3cb7e12f88c7
Create Date: 2024-05-24 15:13:21.526402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a84b8e2d17'
down_revision = '3cb7e12f88c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_start')
        batch_op.create_index(batch_op.f('ix_events_start'), ['start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_start'))
        batch_op.create_index('ix_events_start', ['start'], unique=False)

    # ### end Alembic commands ###
