"""changed events.sql

Revision ID: f761424feaed
Revises: 645f3889296d
Create Date: 2024-05-22 21:58:47.674635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f761424feaed'
down_revision = '645f3889296d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_start', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('instance_end', sa.DateTime(), nullable=False))
        batch_op.drop_column('duration')
        batch_op.drop_column('instance_date')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_start')
        batch_op.create_index(batch_op.f('ix_events_start'), ['start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_start'))
        batch_op.create_index('ix_events_start', ['start'], unique=False)

    with op.batch_alter_table('event_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('instance_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=False))
        batch_op.drop_column('instance_end')
        batch_op.drop_column('instance_start')

    # ### end Alembic commands ###
